### ISSUE TITLE
Create Ditto

### ISSUE THREAD

**Issue by CSung28** [CSung28/branch-practice#1]
## Explanation
I want to make a Ditto, one of the pokemon.

## Tasks
- [x] writing Ditto concept
- [x] design appearance of Ditto
- [x] making Ditto's skills

## Reference
www.google.com
